base_url: /fosslight-system-guide-en
title: FOSSLight System 
lang: ko
description: FOSSLight System English Guide

remote_theme: fosslight/jekyll-rtd-theme

top_link: "https://fosslight.github.io/fosslight-system-guide"
top_link_word: "Ko"

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
