base_url: /fosslight-system-guide-en
title: FOSSLight
lang: en
description: FOSSLight English Guide

remote_theme: fosslight/jekyll-rtd-theme

top_link: "https://fosslight.github.io/fosslight-system-guide"
top_link_word: "Kor"

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
