base_url: /fosslight-guide-en
title: FOSSLight Guide
lang: en
description: FOSSLight English Guide

remote_theme: fosslight/guide_theme

top_link: "https://fosslight.github.io/fosslight-guide"
top_link_word: "Korean"

addons_title: "FOSSLight Homepage"
addons_url: "https://fosslight.org"

google:
  gtag: UA-196813776-4

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
