base_url: /fosslight-guide-en
title: FOSSLight
lang: en
description: FOSSLight English Guide

remote_theme: fosslight/guide_theme

top_link: "https://fosslight.github.io/fosslight-guide"
top_link_word: "Kor"

google:
  gtag: UA-196813776-4

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
